FROM php:7.4-fpm

# Copy composer.lock and composer.json
COPY composer.lock composer.json /var/www/

# Set working directory
WORKDIR /var/www

# Install dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    default-mysql-client \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    locales \
    zip \
    jpegoptim optipng pngquant gifsicle \
    vim \
    unzip \
    git \
    curl \
    python2 \
    npm \
    nano \
    libonig-dev \
    libzip-dev \
    inetutils-ping \
    libmagickcore-dev \
    libmagickwand-dev



#RUN echo 'export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "/home/www/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"' >> ~/.bashrc; echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm' >> ~/.bashrc; nvm install 18; nvm use 18
# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*


# Install extensions
RUN pecl install imagick && docker-php-ext-enable imagick
RUN docker-php-ext-install pdo_mysql mbstring zip exif pcntl
RUN docker-php-ext-configure gd
RUN docker-php-ext-install gd

# Add user for laravel application
RUN groupadd -g 1000 www
RUN useradd -u 1000 -ms /bin/bash -g www www



RUN su www -c 'curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash'

RUN echo 'export NVM_DIR="$([ -z "/var/www/.nvm" ] && printf %s "/var/www/.nvm" || printf %s "/var/www/.nvm/nvm")"' >> /var/www/.bashrc; echo '[ -s /var/www/.nvm/nvm.sh" ] && \. "/var/www/.nvm/nvm.sh" # This loads nvm' >> /var/www/.bashrc;   echo "nvm use 14" >> /var/www/.bashrc

RUN su www -c 'source ~/.nvm/nvm.sh; nvm install 14; npm install --global yarn; npm install -g sass; npm --global install typescript'

RUN curl -sS https://getcomposer.org/installer | php \
        && mv composer.phar /usr/local/bin/ \
        && ln -s /usr/local/bin/composer.phar /usr/local/bin/composer

# Copy existing application directory contents
COPY . /var/www

# Copy existing application directory permissions
COPY --chown=www:www . /var/www
# Change current user to www
USER www
# Expose port 9000 and start php-fpm server
EXPOSE 9000
CMD ["php-fpm"]
